// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComputoCreate(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComputoCreate'](arg1, arg2, arg3);
}

export function ComputoList() {
  return window['go']['app']['App']['ComputoList']();
}

export function DB() {
  return window['go']['app']['App']['DB']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}
