// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDB() {
  return window['go']['app']['App']['BackupDB']();
}

export function ComponenteManoObraCreate(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComponenteManoObraCreate'](arg1, arg2, arg3);
}

export function ComponenteManoObraDelete(arg1) {
  return window['go']['app']['App']['ComponenteManoObraDelete'](arg1);
}

export function ComponenteManoObraGet(arg1) {
  return window['go']['app']['App']['ComponenteManoObraGet'](arg1);
}

export function ComponenteManoObraList() {
  return window['go']['app']['App']['ComponenteManoObraList']();
}

export function ComponenteManoObraListPaged(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComponenteManoObraListPaged'](arg1, arg2, arg3);
}

export function ComponenteManoObraUpdate(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ComponenteManoObraUpdate'](arg1, arg2, arg3, arg4);
}

export function ComponenteMaterialCreate(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComponenteMaterialCreate'](arg1, arg2, arg3);
}

export function ComponenteMaterialDelete(arg1) {
  return window['go']['app']['App']['ComponenteMaterialDelete'](arg1);
}

export function ComponenteMaterialGet(arg1) {
  return window['go']['app']['App']['ComponenteMaterialGet'](arg1);
}

export function ComponenteMaterialList() {
  return window['go']['app']['App']['ComponenteMaterialList']();
}

export function ComponenteMaterialListPaged(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComponenteMaterialListPaged'](arg1, arg2, arg3);
}

export function ComponenteMaterialUpdate(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ComponenteMaterialUpdate'](arg1, arg2, arg3, arg4);
}

export function ComputoConfirm(arg1) {
  return window['go']['app']['App']['ComputoConfirm'](arg1);
}

export function ComputoCreate(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComputoCreate'](arg1, arg2, arg3);
}

export function ComputoCreateNewVersionFrom(arg1) {
  return window['go']['app']['App']['ComputoCreateNewVersionFrom'](arg1);
}

export function ComputoDeleteSeries(arg1) {
  return window['go']['app']['App']['ComputoDeleteSeries'](arg1);
}

export function ComputoGet(arg1) {
  return window['go']['app']['App']['ComputoGet'](arg1);
}

export function ComputoItemMaterialExtraAdd(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ComputoItemMaterialExtraAdd'](arg1, arg2, arg3, arg4);
}

export function ComputoItemMaterialExtraDelete(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComputoItemMaterialExtraDelete'](arg1, arg2, arg3);
}

export function ComputoItemMaterialExtraList(arg1, arg2) {
  return window['go']['app']['App']['ComputoItemMaterialExtraList'](arg1, arg2);
}

export function ComputoList() {
  return window['go']['app']['App']['ComputoList']();
}

export function ComputoRubroItemsAdd(arg1, arg2, arg3) {
  return window['go']['app']['App']['ComputoRubroItemsAdd'](arg1, arg2, arg3);
}

export function ComputoRubroItemsSetCantidad(arg1, arg2) {
  return window['go']['app']['App']['ComputoRubroItemsSetCantidad'](arg1, arg2);
}

export function ComputoRubroItemsTrash(arg1) {
  return window['go']['app']['App']['ComputoRubroItemsTrash'](arg1);
}

export function ComputoRubroTrashEmpty(arg1) {
  return window['go']['app']['App']['ComputoRubroTrashEmpty'](arg1);
}

export function ComputoRubroTrashList(arg1) {
  return window['go']['app']['App']['ComputoRubroTrashList'](arg1);
}

export function ComputoRubroTrashRestore(arg1) {
  return window['go']['app']['App']['ComputoRubroTrashRestore'](arg1);
}

export function ComputoRubrosAdd(arg1, arg2) {
  return window['go']['app']['App']['ComputoRubrosAdd'](arg1, arg2);
}

export function ComputoRubrosDelete(arg1) {
  return window['go']['app']['App']['ComputoRubrosDelete'](arg1);
}

export function ComputoRubrosReorder(arg1, arg2) {
  return window['go']['app']['App']['ComputoRubrosReorder'](arg1, arg2);
}

export function ComputoSetComitenteDescripcion(arg1, arg2) {
  return window['go']['app']['App']['ComputoSetComitenteDescripcion'](arg1, arg2);
}

export function ComputoSetSuperficie(arg1, arg2) {
  return window['go']['app']['App']['ComputoSetSuperficie'](arg1, arg2);
}

export function DB() {
  return window['go']['app']['App']['DB']();
}

export function ExportComputoCSVAndSave(arg1, arg2) {
  return window['go']['app']['App']['ExportComputoCSVAndSave'](arg1, arg2);
}

export function ExportComputoRubrosCSVAndSave(arg1) {
  return window['go']['app']['App']['ExportComputoRubrosCSVAndSave'](arg1);
}

export function ExportQuickItemEstimateCSVAndSave(arg1, arg2) {
  return window['go']['app']['App']['ExportQuickItemEstimateCSVAndSave'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ItemCatalogCreate(arg1, arg2) {
  return window['go']['app']['App']['ItemCatalogCreate'](arg1, arg2);
}

export function ItemCatalogDelete(arg1) {
  return window['go']['app']['App']['ItemCatalogDelete'](arg1);
}

export function ItemCatalogGet(arg1) {
  return window['go']['app']['App']['ItemCatalogGet'](arg1);
}

export function ItemCatalogList() {
  return window['go']['app']['App']['ItemCatalogList']();
}

export function ItemCatalogListPaged(arg1, arg2, arg3) {
  return window['go']['app']['App']['ItemCatalogListPaged'](arg1, arg2, arg3);
}

export function ItemCatalogUpdate(arg1, arg2, arg3) {
  return window['go']['app']['App']['ItemCatalogUpdate'](arg1, arg2, arg3);
}

export function ItemCompositionAddManoObra(arg1, arg2, arg3) {
  return window['go']['app']['App']['ItemCompositionAddManoObra'](arg1, arg2, arg3);
}

export function ItemCompositionAddMaterial(arg1, arg2, arg3) {
  return window['go']['app']['App']['ItemCompositionAddMaterial'](arg1, arg2, arg3);
}

export function ItemCompositionDeleteManoObra(arg1, arg2) {
  return window['go']['app']['App']['ItemCompositionDeleteManoObra'](arg1, arg2);
}

export function ItemCompositionDeleteMaterial(arg1, arg2) {
  return window['go']['app']['App']['ItemCompositionDeleteMaterial'](arg1, arg2);
}

export function ItemCompositionListManoObra(arg1) {
  return window['go']['app']['App']['ItemCompositionListManoObra'](arg1);
}

export function ItemCompositionListMaterials(arg1) {
  return window['go']['app']['App']['ItemCompositionListMaterials'](arg1);
}

export function ItemCompositionSetManoObraDosaje(arg1, arg2, arg3) {
  return window['go']['app']['App']['ItemCompositionSetManoObraDosaje'](arg1, arg2, arg3);
}

export function ItemCompositionSetMaterialDosaje(arg1, arg2, arg3) {
  return window['go']['app']['App']['ItemCompositionSetMaterialDosaje'](arg1, arg2, arg3);
}

export function ManoObraAll(arg1) {
  return window['go']['app']['App']['ManoObraAll'](arg1);
}

export function MaterialsAll(arg1) {
  return window['go']['app']['App']['MaterialsAll'](arg1);
}

export function QuickItemEstimate(arg1, arg2) {
  return window['go']['app']['App']['QuickItemEstimate'](arg1, arg2);
}

export function RubroCatalogCreate(arg1) {
  return window['go']['app']['App']['RubroCatalogCreate'](arg1);
}

export function RubroCatalogDelete(arg1) {
  return window['go']['app']['App']['RubroCatalogDelete'](arg1);
}

export function RubroCatalogGet(arg1) {
  return window['go']['app']['App']['RubroCatalogGet'](arg1);
}

export function RubroCatalogList() {
  return window['go']['app']['App']['RubroCatalogList']();
}

export function RubroCatalogListPaged(arg1, arg2, arg3) {
  return window['go']['app']['App']['RubroCatalogListPaged'](arg1, arg2, arg3);
}

export function RubroCatalogUpdate(arg1, arg2) {
  return window['go']['app']['App']['RubroCatalogUpdate'](arg1, arg2);
}
