// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {sql} from '../models';

export function ComputoCreate(arg1:string,arg2:number,arg3:string):Promise<dto.ComputoCreateResultDTO>;

export function ComputoList():Promise<Array<dto.ComputoListRowDTO>>;

export function DB():Promise<sql.DB>;

export function Greet(arg1:string):Promise<string>;
